export const JOB_STATES=["QUEUED","ANALYZING","STORYBOARDING","GENERATING_VISUALS","GENERATING_AUDIO","COMPOSITING","RENDERING","COMPLETE","ERROR"];
export const canDirectIdea=idea=>typeof idea==="string"&&idea.trim().length>0;
const cue=(start,end,narrationAnchor,visualChange)=>({start,end,narrationAnchor,visualChange});
const splitSentences=text=>text.replace(/\s+/g," ").trim().split(/(?<=[.!?])\s+/).filter(Boolean);
const words=text=>text.toLowerCase().match(/[a-zà-ÿ0-9][a-zà-ÿ0-9'-]*/gi)||[];
function entities(text){const w=words(text).filter(x=>x.length>4);return [...new Set(w)].slice(0,5)}
function sceneFor(text,i,total,count){const role=i===0?"hook":i===count-1?"takeaway":i%3===1?"context":i%3===2?"explanation":"process";const purpose=i===0?"Establish the central idea":i===count-1?"Consolidate the takeaway":i%3===1?"Build the context":i%3===2?"Explain the key concept":"Show how the idea works";const visual=i===0?"opening statement with one dominant concept":i===count-1?"final summary that reconnects the ideas":i%3===1?"clear comparison of the main ideas":"concrete topic-specific elements arranged to explain the relationship";return{id:"scene-"+String(i+1).padStart(2,"0"),durationSeconds:Math.max(3,Math.round(total)),narration:text,pedagogical:{purpose,mainConcept:text.slice(0,90),viewerMustUnderstand:[text],narrativeRole:role},semantics:{entities:entities(text),actions:["introduce","explain","connect"],relations:["topic relationship"],initialState:i===0?"topic not yet introduced":"previous scene established context",finalState:"viewer has a clearer mental model",structure:i===0?"opening":i===count-1?"conclusion":"explanation"},visualDirection:{visualLanguage:"editorial explainer",composition:visual,camera:"stable framing for comprehension",motionPurpose:"reveal or emphasize information as it is narrated",transition:i===0?"clean opening":"carry one visual idea into the next scene",persistentEntities:entities(text),assetRequirements:["topic-specific visual elements","legible labels","simple diagrams where useful"]},cues:[cue(0,Math.max(1,total*.45),text.slice(0,35),"Introduce the main visual idea."),cue(Math.max(1,total*.45),total,text.slice(35,75),"Emphasize the key relationship or conclusion.")]}}
export function buildSemanticStoryboard({idea,language="en",duration=60,mode="youtube"}){if(!canDirectIdea(idea))throw new Error("Please enter a script.");const sentences=splitSentences(idea);const count=Math.min(8,Math.max(3,sentences.length));const chunks=Array.from({length:count},(_,i)=>{const a=Math.floor(i*sentences.length/count),b=Math.floor((i+1)*sentences.length/count);return sentences.slice(a,b).join(" ")||sentences[Math.min(a,sentences.length-1)]||idea});const base=duration/count;const scenes=chunks.map((x,i)=>sceneFor(x,i,base,count));return{title:(sentences[0]||"NEVORA Educational Video").replace(/[.!?]+$/,"").slice(0,90),language,mode,durationSeconds:duration,sourceIdea:idea.trim(),visualBible:{style:"clean editorial educational",palette:"neutral base with NEVORA lime for emphasis",continuity:["consistent typography","topic-specific visual language","clear visual hierarchy"],forbidden:["decorative particles","meaningless node graphs","generic AI wallpaper","visuals unrelated to narration"]},scenes:scenes.map(s=>({...s,durationSeconds:+base.toFixed(1),cues:s.cues.map(c=>({...c,start:+c.start.toFixed(1),end:+c.end.toFixed(1)}))}))}}
export function validateStoryboard(storyboard){const e=[];if(!storyboard.scenes?.length)e.push("No scenes generated");for(const s of storyboard.scenes||[]){if(!s.narration)e.push(s.id+": missing narration");if(!s.visualDirection?.composition)e.push(s.id+": missing visual direction");if(!s.cues?.length)e.push(s.id+": missing cues")}return e}
export function createRenderManifest(storyboard){return{format:{container:"mp4",videoCodec:"h264",audioCodec:"aac",width:storyboard.mode==="short"?1080:1920,height:storyboard.mode==="short"?1920:1080,aspectRatio:storyboard.mode==="short"?"9:16":"16:9"},status:"READY_FOR_LOCAL_RENDER",scenes:storyboard.scenes.map(s=>({sceneId:s.id,durationSeconds:s.durationSeconds,narration:s.narration,visualCues:s.cues,requiredAssets:s.visualDirection.assetRequirements}))}}
